project:
  name: quickstart-cloudbees-ci
  owner: dschott@cloudbees.com
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  #package_lambda: false  # uncomment to save time by not packaging unchanged lambdas
  regions:
  - us-east-1
  - us-east-2
  - us-west-2
  - eu-west-1
  - ca-central-1
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    AvailabilityZones: $[taskcat_genaz_3]
  template: templates/cloudbees-ci-entrypoint-new-vpc.template.yaml
tests:
  default:
    regions:
    - us-east-1
