AWSTemplateFormatVersion: 2010-09-09
Description: Deploys CloudBees CI into an existing Kubernetes cluster (qs-1pipqrqje)
Metadata: { cfn-lint: { config: { ignore_checks: [E3001,E1019] } } }
Parameters:
  EKSClusterName:
    Type: String
  StorageClassName:
    Type: String
  ValueOverrideURL:
    Default: ''
    Type: String
Conditions:
  ValueOverrideURLExists: !Not [!Equals [ !Ref ValueOverrideURL, '' ]]
Mappings:
  CloudBees:
    CI: { Namespace: 'cloudbees-core' }
Resources:
  CloudBeesNamespace:
    Type: AWSQS::Kubernetes::Resource
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: 'default'
      Manifest: !Sub 
        - |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: ${Namespace}
        - Namespace: !FindInMap [CloudBees, CI, Namespace]
          
  CloudBeesCI:
    Type: "AWSQS::Kubernetes::Helm"
    DependsOn: CloudBeesNamespace
    Properties:
      ClusterID: !Ref EKSClusterName
      Repository: https://public-charts.artifacts.cloudbees.com/repository/public/
      Chart: cloudbees/cloudbees-core
      #Version: 3.16.1+a3fdb4ae4e87 # uncomment to use something other than latest
      Name: cloudbees-ci
      Namespace: !FindInMap [CloudBees, CI, Namespace]
      ValueYaml: !Sub |
        OperationsCenter:
          Platform: eks
          Ingress:
            Class: alb
            Annotations:
              alb.ingress.kubernetes.io/scheme: internet-facing
          ExtraConfigMaps:
          - name: cloudbees-referrer
            labels:
              app.kubernetes.io/component: trial-telemetry
            data:
              .cloudbees-referrer.txt: |
                CI on AWS Quick Start
          ExtraVolumes:
          - name: cloudbees-referrer
            configMap:
              name:  cloudbees-referrer
          ExtraVolumeMounts:
          - name: cloudbees-referrer
            mountPath: /var/jenkins_home/.cloudbees-referrer.txt
            subPath: .cloudbees-referrer.txt
            readOnly: true
        Agents:
          SeparateNamespace:
            Enabled: true
            Create: true
            Name: cloudbees-agents
        Persistence:
          StorageClass: ${StorageClassName}
      # TODO remove conditional when empty string is checked in:
      # https://github.com/aws-quickstart/quickstart-helm-resource-provider/blob/bec748ffaf30cab420ddbe19b5d2752cb9a43ba7/cmd/resource/utils.go#L133
      ValueOverrideURL: !If
        - ValueOverrideURLExists
        - !Ref ValueOverrideURL
        - !Ref AWS::NoValue

  CloudBeesCIURL:
    DependsOn: CloudBeesCI
    Type: "AWSQS::Kubernetes::Get"
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: !FindInMap [CloudBees, CI, Namespace]
      Name: 'ingress/cjoc'
      JsonPath: '{.status.loadBalancer.ingress[0].hostname}'

Outputs:
  CloudBeesCIURL:
    Value: !Sub "http://${CloudBeesCIURL.Response}/cjoc"