AWSTemplateFormatVersion: 2010-09-09
Description: Deploys an EFS file system and efs-provisioner (qs-1pipqrqhi)

Parameters:
  EKSClusterName:
    Type: String
  InitialNodeGroupSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  ProvisionedThroughputInMibps:
    Type: Number
  PrivateSubnet1ID:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2ID:
    Type: String
    Default: ""
  PrivateSubnet3ID:
    Type: String
    Default: ""

Conditions:
  3AZDeployment: !Not [!Equals [!Ref PrivateSubnet3ID, ""]]
  2AZDeployment: !Or
    - !Not [!Equals [!Ref PrivateSubnet2ID, ""]]
    - !Not [!Equals [!Ref PrivateSubnet3ID, ""]]

Resources:
  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties: 
      Encrypted: true
      FileSystemTags:
      - Key: Name
        Value: cloudbees-core-efs-filesystem
      PerformanceMode: generalPurpose
      ProvisionedThroughputInMibps: !Ref ProvisionedThroughputInMibps
      ThroughputMode: provisioned
  MountTargetPrivateSubnet1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SecurityGroups: [ !Ref InitialNodeGroupSecurityGroup ]
      SubnetId: !Ref PrivateSubnet1ID
  MountTargetPrivateSubnet2:
    Condition: 2AZDeployment
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SecurityGroups: [ !Ref InitialNodeGroupSecurityGroup ]
      SubnetId: !Ref PrivateSubnet2ID
  MountTargetPrivateSubnet3:
    Condition: 3AZDeployment
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SecurityGroups: [ !Ref InitialNodeGroupSecurityGroup ]
      SubnetId: !Ref PrivateSubnet3ID
  EFSProvisioner:
    Type: "AWSQS::Kubernetes::Helm"
    Properties:
      ClusterID: !Ref EKSClusterName
      Chart: stable/efs-provisioner
      Name: efs-provisioner
      Values:
        efsProvisioner.efsFileSystemId: !Ref EFSFileSystem
        efsProvisioner.awsRegion: !Ref "AWS::Region"
        efsProvisioner.provisionerName: aws-quickstart/aws-efs
        efsProvisioner.storageClass.name: aws-efs
        nodeSelector.partition: masters

Outputs:
  EFSFileSystemID:
    Description: EFS file system ID
    Value: !Ref EFSFileSystem